spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: c5cec2801bcc7a2ce66d7bdb61b04dd9
          naver:
            clientId: 'CLIENT ID'
          google:
            clientId: 'CLIENT ID'
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
           devUser:
            oauthId: 'oauthId'
          naver:
            devUser:
             oauthId: 'oauthId'
          google:
              devUser:
               oauthId: 'oauthId'
          facebook:
              devUser:
               oauthId: 'oauthId'