spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 400aa6a649222fdeb2bb9aeaf3a6782f
          naver:
            clientId: mTuGjsScNoWLx5yz3ptE
            client-secret: 9KFnXgzo7x
          google:
            clientId: 506584560424-b2rng2v40fgg5h2st2do93scflisdt0h.apps.googleusercontent.com
            client-secret: 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
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUser:
              oauthId: 'oauthId'
          naver:
            devUser:
              oauthId: 'oauthId'
          google:
            devUser:
              oauthId: 'oauthId'