spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: 400aa6a649222fdeb2bb9aeaf3a6782f
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
            devUserOauthId: 'oauthId'