spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: c5cec2801bcc7a2ce66d7bdb61b04dd9
custom:
  security:
    oauth2:
      client:
        registration:
          kakao:
           devUser:
            oauthId: 'oauthId'
            nickname: dd
            profileImgUrl: ""